# docker/docker-compose.yml

version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "TuPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    build:
      context: ../backend
    ports:
      - "5023:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MiBase;User Id=sa;Password=TuPassword123!
      - Redis__Host=redis
    depends_on:
      - sqlserver
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  sql_data:

networks:
  app-network:
    driver: bridge